# Generated by Django 5.2.4 on 2026-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor_intro',
            field=models.TextField(blank=True, verbose_name='튜터 상세 소개 및 경력'),
        ),
    ]
