# Generated by Django 5.2.4 on 2025-10-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_image_url', models.URLField(max_length=500)),
                ('introduction', models.CharField()),
                ('curriculum', models.CharField()),
                ('price', models.IntegerField()),
                ('max_tutees', models.IntegerField()),
                ('status', models.CharField(choices=[('preparing', '준비중'), ('recruiting', '모집중'), ('in_progress', '강의중'), ('finished', '종료')], default='preparing', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tutees', models.ManyToManyField(blank=True, related_name='attending_courses', to='accounts.account')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='accounts.account')),
                ('wish_users', models.ManyToManyField(blank=True, related_name='wished_courses', to='accounts.account')),
            ],
        ),
    ]
