# Generated by Django 5.2.4 on 2025-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
