# Generated by Django 5.2.4 on 2025-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
