# services : 실행하려는 컨테이너들을 정의한다.
# web(Django), db(PostgreSQL), redis,nginx 4개의 서비스
services:
  ###################################
  # BACKEND – Django REST API
  ###################################
  backend:
    # ./api 디렉터리의 Dockerfile을 사용하여 이미지를 빌드한다
    build: ./back-end
    
    container_name : yunissaem-backend
    
    # 컨테이너가 실행될 때 수행할 명령어
    # Gunicorn을 사용하여 Django 애플리케이션을 실행합니다.
    # your_project는 실제 프로젝트 이름으로 변경해야한다.
    command: gunicorn yunissaem_api.wsgi:application --bind 0.0.0.0:8000
    
    # [./back-end:/app] : 호스트의 ./back-end 디렉터리를 컨테이너의 /app 디렉터리와 동기화한다
    # 코드 변경 시 컨테이너를 다시 빌드할 필요가 없다
    volumes:
      - ./back-end:/app
      - static_volume:/app/static
      - media_volume:/app/media
    
    # 8000번 포트를 다른 컨테이너에 노출시킨다.
    # Nginx가 이 포트로 요청을 전달한다.
    # nginx.conf에 django 포트에 대한 내용이 작성되어 있으므로 yml에  따로 작성하지 않아도 된다.
    expose:
      - 8000

    # db와 redis 서비스가 먼저 실행되도록 의존성을 설정합니다.
    depends_on:
      - postgres
      - redis
      
    # Django 애플리케이션이 데이터베이스에 연결하는데 필요한 환경변수들을 설정
    environment:
      DJANGO_SETTINGS_MODULE: yunissaem_api.settings

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

    networks:
      - yuninet

  ###################################
  # PostgreSQL
  ###################################
  postgres:
    image: postgres:15
    container_name: yunissaem-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - yuninet

  ###################################
  # Redis – 로그인 세션 / 채팅 큐
  ###################################
  redis:
    image: redis:7
    container_name: yunissaem-redis
    ports:
      - "6379:6379"
    networks:
      - yuninet
  


  # nginx 컨테이너
  ###################################
  # NGINX – API Reverse Proxy
  ###################################
  nginx:
    container_name: yunissaem-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - yuninet

# postgres_data볼륨을 명시적으로 정의한다
# "우리 프로젝트는 postgres_data라는 이름의 데이터 저장 공간을 공식적으로 사용할거야"
# 라고 선언하고 등록하는 것과 같다.
volumes:
  pgdata:
  static_volume:
  media_volume:

networks:
  yuninet: