# Generated by Django 5.2.4 on 2025-11-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.5, '0.5점'), (1.0, '1.0점'), (1.5, '1.5점'), (2.0, '2.0점'), (2.5, '2.5점'), (3.0, '3.0점'), (3.5, '3.5점'), (4.0, '4.0점'), (4.5, '4.5점'), (5.0, '5.0점')], decimal_places=1, max_digits=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.enrollment')),
            ],
            options={
                'unique_together': {('enrollment',)},
            },
        ),
    ]
