# docker-compose.yml에 정의된 api 서비스의 8000번 포트로 요청을 보낼 서버 그룹의 정의
# docker compose의 내부 DNS 덕분에 서비스 이름(backend)으로 컨테이너에 접근할 수 있음
upstream django {
    server backend:8000;
}

server {
    # 80번 포트에서 들어오는 요청을 처리
    listen 80;

    # 루트 URL(/)로 들어오는 모든 요청을 proxy_pass http://django; 설정을 통해
    # upstram에서 정의한 django 서버 그룹(즉, api컨테이너)으로 전달
    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # API 요청은 전부 Django로
    location /api/ {
        proxy_pass http://backend:8000/;
    }

    # Django static
    location /static/ {
        alias /app/static/; #Django collectstatic 결과
    }

    # Django media
    location /media/ {
        alias /app/media/;
    }

    # 헬스 체크 엔드포인트
    # AWS Load Balancer, docker health check등에 사용
    # location /health {
    #     return 200 "ok";
    # }
}